### ISSUE TITLE
iOS 7.1 problem

### ISSUE THREAD

**Issue by joeldenke** [WebReflection/testardo#12]
I dont know if I am doing it wrong, but I copied your google example into local file app.js and run this in terminal:
testardo --ip=192.168.0.1 --port=4444 --host=google.com --loop=0 app.js

Trying to run with both http and $ in the end, like http://192.168.0.1:4444/$ in both Chrome and Safari on my iPhone 5 with iOS 7.1. It loads the page, but nothing happens. When I test same page locally on the computer it works flawlessly. This was my last hope instead of Silenium Remote WebDriver and SaucyLabs to run my tests natively :P

**Comment by WebReflection** [comment]
1. what inside `app.js`
2. why are you changing the IP ?
3. why are you changing the default `7357` port ?

but most of all … why are you trying to test google.com ?

**Comment by joeldenke** [comment]
1. app.js = google-search.js examples in your github repo
2. Because it wouldnt work with localhost to use on my iPhone in same network
3. Was testing a new port if 7357 maybe was blocked somehow

Your example tested google, so I just copied the code to test it before moving on to my own tests.

**Comment by WebReflection** [comment]
so, let me re-ask: are you sure that is the right IP and why are you changing it since by default testardo goes in `0.0.0.0` which **is** reachable through your intranet?

here what I've just done

`testardo --host=google.com --loop=0 ~/code/testardo/examples/google-search.js`
which output in console resulted in:

```
en0: http://192.168.25.85:7357/$
en1: http://192.168.132.157:7357/$
```

and reaching this page `http://192.168.132.157:7357/$` with any of my browsers or phone worked without problems.

**Comment by joeldenke** [comment]
Yes I am 100 % sure. Yes I tried default ip as well, I just make sure no option is untested. I Did exactly as you did, it Works only locally. The difference is that I am using wifi connection. Could that be the problem? I am testing on iPhone 5 with iOS 7.1.1

**Comment by WebReflection** [comment]
no, wifi is also what I use, there's no other way to test devices otherwise but if you use wifi then you should check that you have only 1 IP shown and that your computer / OS lets external devices connect.

As example, if you can, try with another Mac or PC to connect via same url instead of your phone (ask a friend or something if you don't have one) … also, are you on Mac, Linux, or PC?

**Comment by joeldenke** [comment]
Yes port 7357 is open and listening, and only one ip. I Will try with another device. I am on Linux, distro Ubuntu 13.04.

**Comment by WebReflection** [comment]
it might be a firewall issue then … I haven't had a chance to test Ubuntu yet, I will over the week end (although I just installed the 14.04 LTS :-( )

**Comment by WebReflection** [comment]
I've tested on Ubuntu 14.04 LTS and iOS 7.1.1 as well as every other compatible device just worked.

I haven't changed anything neither installed any extra firewall so I am going to close this for now.

Only thing that comes in my mind, is that iOS is so dumb when you type an IP in the browser you **must** write `http://` before the IP or it won't work.
